# Generated by Django 4.2.1 on 2023-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=255, null=True),
        ),
    ]
